name: Build
run-name: building main library
on: [push]
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Build with CMake
              uses: lukka/run-cmake@v10.6
              with:
                configurePreset: base-win
                buildPreset: base-win
    
